auth:
  hub.kc2288.dynv6.net:4999:
    insecure: true
    username: $USERNAME
    password: $PASSWORD
images:
    # k8s.gcr.io/git-sync/git-sync: hub.kc2288.dynv6.net:4999/git-sync
    # gcr.io/kaniko-project/executor:debug,latest: hub.kc2288.dynv6.net:4999/kaniko-executor
    # k8s.gcr.io/metrics-server/metrics-server: hub.kc2288.dynv6.net:4999/metrics-server
    # k8s.gcr.io/ingress-nginx/controller: hub.kc2288.dynv6.net:4999/ingress-nginx-controller
    # k8s.gcr.io/kube-state-metrics/kube-state-metrics: hub.kc2288.dynv6.net:4999/kube-state-metrics
    # k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner: hub.kc2288.dynv6.net:4999/nfs-subdir-external-provisioner
    # k8s.gcr.io/prometheus-adapter/prometheus-adapter: hub.kc2288.dynv6.net:4999/prometheus-adapter
    k8s.gcr.io/kube-apiserver: hub.kc2288.dynv6.net:4999/kube-apiserver
    k8s.gcr.io/kube-controller-manager: hub.kc2288.dynv6.net:4999/kube-controller-manager
    k8s.gcr.io/kube-scheduler: hub.kc2288.dynv6.net:4999/kube-scheduler
    k8s.gcr.io/kube-proxy: hub.kc2288.dynv6.net:4999/kube-proxy
    k8s.gcr.io/pause: hub.kc2288.dynv6.net:4999/pause
    k8s.gcr.io/etcd: hub.kc2288.dynv6.net:4999/etcd
    coredns/coredns: hub.kc2288.dynv6.net:4999/coredns
