auth:
  hub.kc2288.dynv6.net:4999:
    insecure: true
    username: $USERNAME
    password: $PASSWORD
images:
    # registry.k8s.io/git-sync/git-sync: hub.kc2288.dynv6.net:4999/git-sync
    # gcr.io/kaniko-project/executor:debug,latest: hub.kc2288.dynv6.net:4999/kaniko-executor
    registry.k8s.io/metrics-server/metrics-server: hub.kc2288.dynv6.net:4999/metrics-server/metrics-server
    registry.k8s.io/ingress-nginx/controller: hub.kc2288.dynv6.net:4999/ingress-nginx/controller
    registry.k8s.io/kube-state-metrics/kube-state-metrics: hub.kc2288.dynv6.net:4999/kube-state-metrics/kube-state-metrics
    registry.k8s.io/sig-storage/nfs-subdir-external-provisioner: hub.kc2288.dynv6.net:4999/sig-storage/nfs-subdir-external-provisioner
    registry.k8s.io/prometheus-adapter/prometheus-adapter: hub.kc2288.dynv6.net:4999/prometheus-adapter/prometheus-adapter
    registry.k8s.io/kube-apiserver:/v1.28.../: hub.kc2288.dynv6.net:4999/kube-apiserver
    registry.k8s.io/kube-controller-manager:/v1.28.../: hub.kc2288.dynv6.net:4999/kube-controller-manager
    registry.k8s.io/kube-scheduler:/v1.28.../: hub.kc2288.dynv6.net:4999/kube-scheduler
    registry.k8s.io/kube-proxy:/v1.28.../: hub.kc2288.dynv6.net:4999/kube-proxy
    registry.k8s.io/pause:/3.8/: hub.kc2288.dynv6.net:4999/pause
    registry.k8s.io/etcd:/3.6..-0/: hub.kc2288.dynv6.net:4999/etcd
    coredns/coredns:/v1.9../: hub.kc2288.dynv6.net:4999/coredns/coredns
