# This is a basic workflow to help you get started with Actions

name: image-sync
on:
  push:
    branches: [ rorz99 ]
  pull_request:
    branches: [ rorz99 ]
  schedule:
    - cron: '0 14 * * 1'

env:
  IMAGE_SYNCER_VERSION: v1.4.1
  USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  image-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: install image-sync tool
      run: |
        bash test.sh

    # - name: add sercret to file
    #   run: envsubst < config_source.yaml > config.yaml

    - name: test service
      run: while pgrep vpnclient >/dev/null; do sleep 901;done
